create and style see blog page for donation app
GSG-CF05/DonationApp-Team-4 pull request #16
Opened 2022-02-07 23:10 UTC by omaraburabie3

relates #9

2022-02-08 10:29 UTC, emanjaber requested changes
Great job, Omar!
These are some changes that I hope you will make

2022-02-08 10:29 UTC, emanjaber commented on See blog/see-blog.css
> +  margin-top: 20px;
There is too much space between the `header` and the `top-par` section, so you can delete `margin-top`

2022-02-08 10:29 UTC, emanjaber commented on See blog/see-blog.html
> +      <div class="person"><img src="../images\Ellipse 36 (1).png" /></div>
The `img` is too small, you need to make it bigger, especially in the desktop size

2022-02-08 10:29 UTC, emanjaber commented on See blog/see-blog.css
> +    height: 500px;
You need to fix the size of this photo in tablet size, I think `height: 300px` will be suitable

2022-02-08 10:40 UTC, Bas-Shiekh commented on See blog/see-blog.css
> +  top: 74px;
delete left and top  because they don't change anything

2022-02-08 22:51 UTC, Bas-Shiekh approved these changes

2022-02-08 22:51 UTC, Bas-Shiekh commented on See blog/see-blog.css
> +    background: url(../images/Rectangle\ 1485.png);
don't repeat **background** in media query because that make many issues in this site

2022-02-08 23:17 UTC, Bakeza approved these changes

2022-02-08 23:23 UTC, SaraDahman approved these changes

2022-02-09 08:42 UTC, emanjaber approved these changes
**Well done, Omar! 🎉**

2022-02-09 11:27 UTC, merged