Creating and style for inside fundraiser page
GSG-CF05/DonationApp-Team-4 pull request #17
Opened 2022-02-08 13:37 UTC by Bakeza

relate #8

2022-02-08 13:38 UTC, Bas-Shiekh submitted a review, later dismissed

2022-02-08 16:18 UTC, emanjaber requested changes
**Great job, Bakeza!**

You need to make changes at comment with mark (4).  _html file_

Comments with mark (1), (2), and (3) are suggestions, take a look at them.  _css file_

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        padding: 0 2rem;
Try making these changes for tablet size and let me know if you think it's better, like I think. 
I will mark them with (1)
**(1)**
`padding: 1rem 3rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        margin: 1rem 2rem;
**(1)**
`margin: 1rem 3rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        padding: 0 2rem;
**(1)**
`padding: 1rem 3rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        padding: 0 2rem;
**(1)**
`padding: 0 3rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.html
> +        <img class="line" src="img/line.png" alt="">
**(4)**
This line represents progress that will constantly change in reality, so we can't put it as a static image.

Instead of `img` we can use `div` and `span` like this:
`<div><span style="width: 95%;"> </span></div>`

Therefore, the width will change according to the change in the data.

And of course, giving `div` and `span` their own different colors so the progress is clear.

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        padding: 0 2rem;
Try making these changes for desktop size and let me know if you think it's better, like I think.
I will mark them with (2)
**(2)**
`padding: 1rem 4rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        margin: 1rem 2rem;
**(2)**
`margin: 1rem 4rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        padding: 0 2rem;
**(2)**
`padding: 1rem 4rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        padding: 0 2rem;
**(2)**
`padding: 0 4rem;`

2022-02-08 16:18 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +    margin-top: 10px;
**(3)**
Try this it might be better

`margin: 20px 0;`

2022-02-08 23:28 UTC, SaraDahman submitted a review, later dismissed

2022-02-08 23:32 UTC, omaraburabie3 approved these changes, later dismissed

2022-02-09 11:31 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +        padding: 0 2rem;
**You missed this one** @Bakeza

2022-02-09 11:31 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +    border-width: 1px;
Add this style:
`background-color: #C2E6D9;`

2022-02-09 11:31 UTC, emanjaber commented on Inside fundraiser1/inside-fundraiser1.css
> +    width: 80%;
It should be:
`width: 95%;`

2022-02-09 13:49 UTC, emanjaber approved these changes
**Well done Bakeza! 🎉**

2022-02-09 13:54 UTC, Bas-Shiekh approved these changes

2022-02-09 13:54 UTC, SaraDahman approved these changes

2022-02-09 13:54 UTC, omaraburabie3 approved these changes

2022-02-09 14:09 UTC, merged